title: elbae on github.io

author:   #

email:   #

description: Personal space connected with github. Nothing is related to the company I work for if not specifically underlined.

baseurl: "/" # the subpath of your site, e.g. /blog

url: "http://elbae.github.io"
#url: "http://127.0.0.1:4000" #"http://elbae.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  


header_pages:
  - index.markdown
  - notes.markdown
  - whoami.markdown
